### ISSUE TITLE
Any plans to port IIS2ICLX library and example?

### ISSUE THREAD

**Issue by oms-george-popa** [stm32duino/IIS2MDC#4]
The module I'm trying to interface is IIS2ICLX but the _reg driver code seems too convoluted to work with. Any plans to port the IIS2ICLX into Arduino?

**Comment by cparata** [comment]
Hi @oms-george-popa ,
if you are talking about IIS2ICLX, this is not the right point to discuss it. IIS2ICLX is a 2-axis inclinometer that is not still supported in the Arduino environment and, unfortunately, I don't have bandwidth to work on it in the next months. This library is instead for a magnetometer.
Best Regards,
Carlo
